/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Group {
  'id' : GroupId,
  'members' : Array<UserId>,
  'messages' : Array<Message>,
  'name' : string,
}
export type GroupId = string;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : UserId,
  'timestamp' : bigint,
  'reactions' : Array<Reaction>,
}
export type MessageId = bigint;
export interface Reaction { 'userId' : UserId, 'emoji' : string }
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'displayName' : string,
  'avatarId' : [] | [string],
  'lastActive' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReaction' : ActorMethod<[GroupId, MessageId, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string], GroupId>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroupList' : ActorMethod<[], Array<Group>>,
  'getGroupMembers' : ActorMethod<[GroupId], Array<UserId>>,
  'getLastActive' : ActorMethod<[UserId], Time>,
  'getMessageHistory' : ActorMethod<[GroupId, bigint], Array<Message>>,
  'getUserGroups' : ActorMethod<[], Array<Group>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'inviteToGroup' : ActorMethod<[GroupId, UserId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isGroupMember' : ActorMethod<[GroupId], boolean>,
  'leaveGroup' : ActorMethod<[GroupId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[GroupId, string], Message>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];